Repository prgrms-web-devcourse-final-project/WEB5_7_7STARBALL_BE, pull requests merged in 2025-07, with the labels that each got.

#34 feat: spot service
  build.gradle
  src/main/java/sevenstar/marineleisure/forecast/domain/Fishing.java
  src/main/java/sevenstar/marineleisure/forecast/domain/Mudflat.java
  src/main/java/sevenstar/marineleisure/forecast/domain/Scuba.java
  src/main/java/sevenstar/marineleisure/forecast/domain/Surfing.java
  src/main/java/sevenstar/marineleisure/forecast/repository/FishingRepository.java
  src/main/java/sevenstar/marineleisure/forecast/repository/MudflatRepository.java
  src/main/java/sevenstar/marineleisure/forecast/repository/ScubaRepository.java
  src/main/java/sevenstar/marineleisure/forecast/repository/SurfingRepository.java
  src/main/java/sevenstar/marineleisure/global/api/khoa/mapper/KhoaMapper.java
  src/main/java/sevenstar/marineleisure/global/api/khoa/service/KhoaApiService.java
  src/main/java/sevenstar/marineleisure/global/api/openmeteo/dto/service/OpenMeteoService.java
  src/main/java/sevenstar/marineleisure/global/api/scheduler/SchedulerService.java
  src/main/java/sevenstar/marineleisure/global/enums/TimePeriod.java
  src/main/java/sevenstar/marineleisure/global/utils/GeoUtils.java
  src/main/java/sevenstar/marineleisure/spot/config/GeoConfig.java
  src/main/java/sevenstar/marineleisure/spot/controller/SpotController.java
  src/main/java/sevenstar/marineleisure/spot/domain/OutdoorSpot.java
  src/main/java/sevenstar/marineleisure/spot/domain/SpotViewQuartile.java
  src/main/java/sevenstar/marineleisure/spot/domain/SpotViewStats.java
  src/main/java/sevenstar/marineleisure/spot/domain/SpotViewStatsId.java
  src/main/java/sevenstar/marineleisure/spot/dto/SpotCreateRequest.java
  src/main/java/sevenstar/marineleisure/spot/dto/SpotDetailReadResponse.java
  src/main/java/sevenstar/marineleisure/spot/dto/SpotDistanceProjection.java
  src/main/java/sevenstar/marineleisure/spot/dto/SpotReadRequest.java
  src/main/java/sevenstar/marineleisure/spot/dto/SpotReadResponse.java
  src/main/java/sevenstar/marineleisure/spot/mapper/SpotMapper.java
  src/main/java/sevenstar/marineleisure/spot/repository/OutdoorSpotRepository.java
  src/main/java/sevenstar/marineleisure/spot/repository/SpotViewQuartileRepository.java
  src/main/java/sevenstar/marineleisure/spot/repository/SpotViewStatsRepository.java
  src/main/java/sevenstar/marineleisure/spot/service/MapService.java
  src/main/java/sevenstar/marineleisure/spot/service/SpotService.java
  src/main/java/sevenstar/marineleisure/spot/service/SpotServiceImpl.java
  src/test/java/sevenstar/marineleisure/global/api/khoa/KhoaApiClientTest.java
  src/test/java/sevenstar/marineleisure/global/utils/GeoUtilsTest.java
  src/test/java/sevenstar/marineleisure/spot/service/SpotServiceTest.java
Labels: feature

#39 Feature/즐겨찾기 CRUD
  build.gradle
  src/main/java/sevenstar/marineleisure/favorite/controller/FavoriteController.java
  src/main/java/sevenstar/marineleisure/favorite/domain/FavoriteSpot.java
  src/main/java/sevenstar/marineleisure/favorite/dto/response/FavoriteGetListDto.java
  src/main/java/sevenstar/marineleisure/favorite/dto/response/FavoritePatchDto.java
  src/main/java/sevenstar/marineleisure/favorite/dto/vo/FavoriteItemVO.java
  src/main/java/sevenstar/marineleisure/favorite/mapper/FavoriteMapper.java
  src/main/java/sevenstar/marineleisure/favorite/repository/FavoriteRepository.java
  src/main/java/sevenstar/marineleisure/favorite/service/FavoriteService.java
  src/main/java/sevenstar/marineleisure/favorite/service/FavoriteServiceImpl.java
  src/main/java/sevenstar/marineleisure/global/exception/enums/AlertErrorCode.java
  src/main/java/sevenstar/marineleisure/global/exception/enums/CommonErrorCode.java
  src/main/java/sevenstar/marineleisure/global/exception/enums/FavoriteErrorCode.java
  src/test/java/sevenstar/marineleisure/favorite/controller/FavoriteControllerTest.java
  src/test/java/sevenstar/marineleisure/favorite/domain/FavoriteSpotTest.java
  src/test/java/sevenstar/marineleisure/favorite/service/FavoriteServiceImplTest.java
Labels: feature

#42 fix: 소셜 로그인 재시도 시 닉네임 UNIQUE 제약 위반 오류 발생
  src/main/java/sevenstar/marineleisure/member/controller/AuthController.java
  src/main/java/sevenstar/marineleisure/member/domain/Member.java
  src/main/java/sevenstar/marineleisure/member/service/AuthService.java
  src/main/java/sevenstar/marineleisure/member/service/MemberService.java
  src/main/java/sevenstar/marineleisure/member/service/OauthService.java
  src/main/resources/application-auth.properties
  src/test/java/sevenstar/marineleisure/member/controller/AuthControllerTest.java
  src/test/java/sevenstar/marineleisure/member/controller/OauthCallbackControllerTest.java
  src/test/java/sevenstar/marineleisure/member/repository/MemberRepositoryTest.java
  src/test/java/sevenstar/marineleisure/member/service/AuthServiceTest.java
  src/test/java/sevenstar/marineleisure/member/service/OauthServiceTest.java
Labels: bug

#49 feat: 즐겨찾기 추가 및 리팩토링
  src/main/java/sevenstar/marineleisure/favorite/repository/FavoriteRepository.java
  src/main/java/sevenstar/marineleisure/forecast/repository/FishingRepository.java
  src/main/java/sevenstar/marineleisure/forecast/repository/MudflatRepository.java
  src/main/java/sevenstar/marineleisure/forecast/repository/ScubaRepository.java
  src/main/java/sevenstar/marineleisure/forecast/repository/SurfingRepository.java
  src/main/java/sevenstar/marineleisure/global/api/khoa/KhoaApiClient.java
  src/main/java/sevenstar/marineleisure/global/api/khoa/dto/item/FishingItem.java
  src/main/java/sevenstar/marineleisure/global/api/khoa/dto/item/KhoaItem.java
  src/main/java/sevenstar/marineleisure/global/api/khoa/dto/item/MudflatItem.java
  src/main/java/sevenstar/marineleisure/global/api/khoa/dto/item/ScubaItem.java
  src/main/java/sevenstar/marineleisure/global/api/khoa/dto/item/SurfingItem.java
  src/main/java/sevenstar/marineleisure/global/api/khoa/service/KhoaApiService.java
  src/main/java/sevenstar/marineleisure/global/api/scheduler/SchedulerService.java
  src/main/java/sevenstar/marineleisure/global/config/SecurityConfig.java
  src/main/java/sevenstar/marineleisure/global/enums/TimePeriod.java
  src/main/java/sevenstar/marineleisure/global/enums/TotalIndex.java
  src/main/java/sevenstar/marineleisure/global/utils/DateUtils.java
  src/main/java/sevenstar/marineleisure/global/utils/FakeUtils.java
  src/main/java/sevenstar/marineleisure/spot/controller/SpotController.java
  src/main/java/sevenstar/marineleisure/spot/dto/FishingReadResponse.java
  src/main/java/sevenstar/marineleisure/spot/dto/SpotDetailReadResponse.java
  src/main/java/sevenstar/marineleisure/spot/dto/SpotReadRequest.java
  src/main/java/sevenstar/marineleisure/spot/dto/SpotReadResponse.java
  src/main/java/sevenstar/marineleisure/spot/mapper/SpotMapper.java
  src/main/java/sevenstar/marineleisure/spot/repository/OutdoorSpotRepository.java
  src/main/java/sevenstar/marineleisure/spot/service/SpotServiceImpl.java
  src/test/java/sevenstar/marineleisure/global/api/ApiClientTest.java
  src/test/java/sevenstar/marineleisure/global/api/ApiServiceIntegrationTest.java
Labels: feature

#87 Refactor/exception hwuan page
  src/main/java/sevenstar/marineleisure/favorite/service/FavoriteServiceImpl.java
  src/main/resources/application-prod.yml
Labels: bug, refactoring

#98 feat: 회원 탈퇴 시 카카오 연결 끊기도 수행하게 구현한다.
  src/main/java/sevenstar/marineleisure/member/service/MemberService.java
  src/main/java/sevenstar/marineleisure/member/service/OauthService.java
  src/test/java/sevenstar/marineleisure/member/service/MemberServiceTest.java
  src/test/java/sevenstar/marineleisure/member/service/OauthServiceTest.java
Labels: feature

#95 refactor: open-meteo 서비스 관련 리팩토링
  src/main/java/sevenstar/marineleisure/global/api/openmeteo/dto/service/OpenMeteoService.java
  src/main/java/sevenstar/marineleisure/spot/dto/detail/provider/ActivityProvider.java
  src/main/java/sevenstar/marineleisure/spot/dto/detail/provider/FishingProvider.java
  src/main/java/sevenstar/marineleisure/spot/dto/detail/provider/MudflatProvider.java
  src/main/java/sevenstar/marineleisure/spot/dto/detail/provider/ScubaProvider.java
  src/main/java/sevenstar/marineleisure/spot/dto/detail/provider/SurfingProvider.java
Labels: refactoring
